name: Build

on:
  push:
  pull_request:

jobs:
  build:
    name: dotnet build
    runs-on: ubuntu-22.04
    container:
      image: mcr.microsoft.com/dotnet/sdk:7.0
    steps:
      - uses: actions/checkout@v3

      - name: Restore dependencies
        run: dotnet restore src/DiIiS-NA/Blizzless.csproj

      - name: Build (Release)
        run: dotnet build src/DiIiS-NA/Blizzless.csproj -c Release --no-restore
