name: Docker Build

on:
  push:
    branches:
      - main
      - test-stable
      - wsl-docker

jobs:
  docker:
    name: docker build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t blizzless-diiis:${{ gitea.sha }} .
